### ISSUE TITLE
Loading Apache2 SSL key

### ISSUE THREAD

**Issue by dmgeurts** [Homas/ioc2rpz.gui#11]
This question is likely more related to docker, but as this is my first encounter with docker containers please bear with me.

I understand that the web UI certificates are stored under /etc/apache2/ssl/ in the container. Is there a way to mount a file on the host to these files in the container? ioc2rpz does this with the config files. Why can't ioc2rpz.gui expose the SSL cert files in the same way to simplify certificate management?

I'm hesitant about editing the container as when updating the container these changes will be lost. Equally, I don't want to run a self-signed certificate on the GUI. Am I missing something really obvious?

Hmmm, as I'm writing this I've spotted the certs under /opt/ioc2rpz/ssl/

So I've symlinked to the certificates under /etc/ssl/ on the host, but now I get:

```
Nov  3 20:27:56 rpz1 ***: cp: not writing through dangling symlink '/etc/apache2/ssl/ioc2_server.pem'
Nov  3 20:27:56 rpz1 ***: cp: not writing through dangling symlink '/etc/apache2/ssl/ioc2_server.key'
Nov  3 20:27:57 rpz1 ***: AH00526: Syntax error on line 150 of /etc/apache2/conf.d/ssl.conf:
Nov  3 20:27:57 rpz1 ***: SSLCertificateFile: file '/etc/apache2/ssl/ioc2_server.pem' does not exist or is empty

```
Can `--remove-destination` be added to the cp statements in [run_ioc2rpz.gui.sh](https://github.com/Homas/ioc2rpz.gui/blob/master/scripts/run_ioc2rpz.gui.sh)

**Comment by Homas** [comment]
The certificates are located in "/etc/apache2/ssl" so you need to mount /opt/ioc2rpz/ssl (or any other directory) to it.
 `--mount type=bind,source=/opt/ioc2rpz/ssl,target=/etc/apache2/ssl`

For simplicity I recommend to use docker compose to run both (ioc2rpz and ioc2rpz.gui) services.
You can find the yaml file in this repository: https://github.com/Homas/ioc2rpz.dc

**Comment by dmgeurts** [comment]
After manually editing the file adding `--remove-destination`, the docker container starts, but complains about the server name. Further inspection shows that the apache2 certs aren't copied yet. May be good to add instructions to create some folders:

/opt/ioc2rpz.gui/export-cfg

And possible others?

**Comment by dmgeurts** [comment]
> The certificates are located in "/etc/apache2/ssl" so you need to mount /opt/ioc2rpz/ssl (or any other directory) to it. `--mount type=bind,source=/opt/ioc2rpz/ssl,target=/etc/apache2/ssl`
> 
> For simplicity I recommend to use docker compose to run both (ioc2rpz and ioc2rpz.gui) services. You can find the yaml file in this repository: https://github.com/Homas/ioc2rpz.dc

Thank you, this mount is in place but what I find is that a symlink is replaced with files from the container.

After creating the symlinks:

```
user@rpz1:~$ sudo ls -al /opt/ioc2rpz/ssl
total 16
drwxr-xr-x 2 root root 4096 Nov  3 23:20 .
drwxr-xr-x 5 root root 4096 Nov  3 14:02 ..
lrwxrwxrwx 1 root root   39 Nov  3 23:19 ioc2_server.key -> /etc/ssl/private/rpz.example.com.key
-rw------- 1 root root 1675 Nov  3 14:05 ioc2_server.key.bkp
lrwxrwxrwx 1 root root   39 Nov  3 23:20 ioc2_server.pem -> /etc/ssl/private/rpz.example.com.pem
-rw------- 1 root root 1480 Nov  3 14:05 ioc2_server.pem.bkp

```

But then after restarting the container:

```
user@rpz1:~$ sudo ls -al /opt/ioc2rpz/ssl
total 24
drwxr-xr-x 2 root root 4096 Nov  3 23:22 .
drwxr-xr-x 5 root root 4096 Nov  3 14:02 ..
-rw------- 1 root root 1675 Nov  3 23:22 ioc2_server.key
-rw------- 1 root root 1675 Nov  3 14:05 ioc2_server.key.bkp
-rw------- 1 root root 1480 Nov  3 23:22 ioc2_server.pem
-rw------- 1 root root 1480 Nov  3 14:05 ioc2_server.pem.bkp
```
Further looking into this I find that symlinked files can't be read from inside the container:

```
bash-5.1# ls -al /etc/apache2/ssl/
total 20
drwxr-xr-x 2 root root 4096 Nov  3 22:28 .
drwxr-xr-x 1 root root 4096 Nov  3 13:05 ..
lrwxrwxrwx 1 root root   39 Nov  3 22:28 ioc2_server.key -> /etc/ssl/private/rpz.be.ipnexia.com.key
-rw------- 1 root root 1675 Nov  3 13:05 ioc2_server.key.bkp
lrwxrwxrwx 1 root root   39 Nov  3 22:28 ioc2_server.pem -> /etc/ssl/private/rpz.be.ipnexia.com.pem
-rw------- 1 root root 1480 Nov  3 13:05 ioc2_server.pem.bkp
bash-5.1# cat /etc/apache2/ssl/ioc2_server.key
cat: /etc/apache2/ssl/ioc2_server.key: No such file or directory
```

**Comment by dmgeurts** [comment]
I guess the easiest solution will be to place the cert files in the respective locations, instead of the default OS locations. I prefer to keep things as standard as possible. Especially when it comes to certificates. Much easier to manage cert renewals if they're consistently in the same place.

**Comment by Homas** [comment]
IMO it is a docker limitation. E.g. see here https://github.com/docker/for-win/issues/5778
If you have all your ssl - certificates in a central location, you can directly mount it to the container. The symlinks should work with the same (or nested) directory.

**Comment by Homas** [comment]
> May be good to add instructions to create some folders:
> 
> /opt/ioc2rpz.gui/export-cfg
> 
> And possible others?

Please check Read.Me. It is documented. Please check if something is missing.
```
To install it manually:
check that all dependencies are installed
create /opt/ioc2rpz.gui, /opt/ioc2rpz.gui/www/io2cfg, /opt/ioc2rpz.gui/export-cfg directories;
download sources and copy them (maintaining the directory structure) to "/opt/ioc2rpz.gui";
create a database by invoking "/opt/ioc2rpz.gui/scripts/init_db.php" script;
create a crontab which will execute "/opt/ioc2rpz.gui/scripts/publish_cfg.php" script every 10 seconds;
configure HTTP server.
Right now ioc2rpz.gui use only SQLite database with a database file stored in "/opt/ioc2rpz.gui/www/io2cfg" folder. Make sure that set up a relevant access permissions to the directory/db-file.

ioc2rpz configuration files are saved to "/opt/ioc2rpz.gui/export-cfg" folder.
```

**Comment by dmgeurts** [comment]
You're absolutely right. Maybe I ended up confused between ioc2rpz and ioc2rpz.gui documentation.

Anyway, thank you for this software. I now need to choose if I'll duplicate the certs, use hard-links or if I move the files and place soft-links in the original locations...

**Comment by Homas** [comment]
you are welcome
