### ISSUE TITLE
Auth from reverse proxy (or LDAP support)

### ISSUE THREAD

**Issue by dmgeurts** [Homas/ioc2rpz.gui#13]
Looking to get LDAP (or OpenID) authentication working I'm using a reverse proxy (OpenResty) with OpenID auth (via Keycloak to LDAP), but would like to avoid users having to log in twice.

Is there a way to either disable the authentication in ioc2rpz.gui or parse it in some way when connecting? SSL client cert, api-keys for each of the three roles or something alike.

**Comment by dmgeurts** [comment]
I guess alternatively I could ditch the docker image and run things natively, but my concern then is regarding code updates.

**Comment by Homas** [comment]
As I can remember there is no configuration option to disable the authentication but the code could be changed to support that. 
ioc2rpz.gui is an admin interface with a very limited number of users supposed to login.
What is the purpose of using a reverse proxy? The container includes apache2 which supports user auth.

**Comment by dmgeurts** [comment]
Yeah, adapting the user auth in Apache there is probably the better option.
