### ISSUE TITLE
Cloned RPZ can't verify with TSIG which works on the source RPZ

### ISSUE THREAD

**Issue by dmgeurts** [Homas/ioc2rpz.gui#16]
How could one go about troubleshooting the following issue? I cloned a zone and only changed the name, nothing else. The Source zone works, but the cloned RPZ zone doesn't. An error is thrown about the TSIG:

```
user@rpz:~$ dig +tcp @10.0.0.35 -y hmac-sha256:tkey_01:********= eu-ordered-bl.ioc2rpz SOA

; <<>> DiG 9.16.1-Ubuntu <<>> +tcp @10.255.12.35 -y hmac-sha256 eu-ordered-bl.ioc2rpz SOA
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32512
;; flags: qr aa rd ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;eu-ordered-bl.ioc2rpz.         IN      SOA

;; ANSWER SECTION:
eu-ordered-bl.ioc2rpz.  604800  IN      SOA     rpz.domain.com. admin.domain.com. 1699728720 7200 3600 259001 7200

;; TSIG PSEUDOSECTION:
tkey_01.             0       ANY     TSIG    hmac-sha256. 1699729966 300 32 ******** 32512 NOERROR 0

;; Query time: 0 msec
;; SERVER: 10.255.12.35#53(10.255.12.35)
;; WHEN: Sat Nov 11 20:12:46 CET 2023
;; MSG SIZE  rcvd: 194

user@rpz:~$ dig +tcp @10.0.0.35 -y hmac-sha256:********= eu-ordered-bl2.ioc2rpz SOA
;; Couldn't verify signature: expected a TSIG or SIG(0)

; <<>> DiG 9.16.1-Ubuntu <<>> +tcp @10.255.12.35 -y hmac-sha256 eu-ordered-bl2.ioc2rpz SOA
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOTAUTH, id: 43853
;; flags: qr rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;eu-ordered-bl2.ioc2rpz.                IN      SOA

;; Query time: 0 msec
;; SERVER: 10.0.0.35#53(10.0.0.35)
;; WHEN: Sat Nov 11 20:12:50 CET 2023
;; MSG SIZE  rcvd: 40
;; WARNING -- Some TSIG could not be validated
```

The docker journal logs:

```
Nov 11 20:12:46 rpz.domain.com c7735b7e2425[37564]: CEF:0|ioc2rpz|ioc2rpz|1.1.2.3-2020123101|000202|DNS Query|3|src=10.0.0.35 spt=46371 proto=tcp qname="eu-ordered-bl.ioc2rpz" qtype="SOA" qclass="IN" tsigkey="tkey_01."
Nov 11 20:12:46 rpz.domain.com c7735b7e2425[37564]: Found Key ... Good timestamp ... Valid MAC
Nov 11 20:12:50 rpz.domain.com c7735b7e2425[37564]: CEF:0|ioc2rpz|ioc2rpz|1.1.2.3-2020123101|000202|DNS Query|3|src=10.0.0.35 spt=52137 proto=tcp qname="eu-ordered-bl2.ioc2rpz" qtype="SOA" qclass="IN" tsigkey="tkey_01."
Nov 11 20:12:50 rpz.domain.com c7735b7e2425[37564]: CEF:0|ioc2rpz|ioc2rpz|1.1.2.3-2020123101|000120|RPZ not found|5|src=10.0.0.35 spt=52137 proto=tcp qname="eu-ordered-bl2.ioc2rpz" qtype="SOA" qclass="IN" tsigkey="tkey_01." msg=[]
```

The first query finds the key but the second complains: `RPZ not found`.

**Comment by Homas** [comment]
Please share the logs from the service (re)start and the configuration file.

**Comment by dmgeurts** [comment]
Restart of the docker service or just ioc2rpz?

It seems ioc2rpz.cnf isn't fully updated by ioc2rpz.gui. It only updates the `config generated by ioc2rpz.gui` line.

**Comment by Homas** [comment]
> Restart of the docker service or just ioc2rpz?

restart ioc2rpz container

> It seems ioc2rpz.cnf isn't fully updated by ioc2rpz.gui. It only updates the `config generated by ioc2rpz.gui` line.

I'm not following your comment.
ioc2rpz.gui should have rw access to the config file, ioc2rpz should have ro access to it.

**Comment by dmgeurts** [comment]
When I clone an RPZ in ioc2rpz-gui, it only updates the first line of the ioc2rpz.cnf. So it can write the file. It just doesn't add a new {rpz} line to the config. If I add a new source it's not added either.

**Comment by dmgeurts** [comment]
Both ioc2rpx and ioc2rpz.gui were deployed two years ago. Maybe it's time I updated them?

**Comment by Homas** [comment]
> Both ioc2rpx and ioc2rpz.gui were deployed two years ago. Maybe it's time I updated them?

there were a few bugs were fixed since than but I don't remember anything related.


> When I clone an RPZ in ioc2rpz-gui, it only updates the first line of the ioc2rpz.cnf. So it can write the file. It just doesn't add a new {rpz} line to the config. If I add a new source it's not added either.

do you mean the comment line "ioc2rpz server io2core-de1 config generated by ioc2rpz.gui at" is only saved? Did you check other settings (e.g. your db-file may be corrupted)?

**Comment by dmgeurts** [comment]
Yes, only the first line gets updated. If I add a key to an RPZ it will add a line for the second key. but there are no changes to the sources or RPZs in the config.

How do I check the db-file?

One thing I have noticed, but probably is unrelated, is that the SSL pem file contains an expired certificate. I'll fix that this morning by setting up ipa-getcert with the proper post-save command string.

**Comment by dmgeurts** [comment]
Running `sudo docker pull pvmdel/ioc2rpz` doesn't seem to update the image.

```
user@rpz:~$ sudo docker pull pvmdel/ioc2rpz
Using default tag: latest
latest: Pulling from pvmdel/ioc2rpz
Digest: sha256:726c03f70dc4370c49894afc5ab2c8b18f04cc06d63963d86602eedf85649682
Status: Image is up to date for pvmdel/ioc2rpz:latest
docker.io/pvmdel/ioc2rpz:latest
```

Docker journal output:

```
Nov 13 16:51:53 rpz.domain.com c7735b7e2425[2981461]: Exec: /usr/local/lib/erlang/erts-11.2/bin/erlexec -noinput +Bd -boot /opt/ioc2rpz/_build/default/rel/ioc2rpz/releases/1.1.2.3-2020123101/start -mode embedded -boot_var SYSTEM_LIB_DIR /usr/local/lib/erlang/lib -config /opt/ioc2rpz/_build/default/rel/ioc2rpz/releases/1.1.2.3-2020123101/sys.config -args_file /opt/ioc2rpz/_build/default/rel/ioc2rpz/releases/1.1.2.3-2020123101/vm.args -- foreground
Nov 13 16:51:53 rpz.domain.com c7735b7e2425[2981461]: Root: /opt/ioc2rpz/_build/default/rel/ioc2rpz
Nov 13 16:51:53 rpz.domain.com c7735b7e2425[2981461]: /opt/ioc2rpz/_build/default/rel/ioc2rpz
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]: Env ip4: [] ip6: [] conf: "./cfg/ioc2rpz.conf" db: "/opt/ioc2rpz/db" cwd: "/opt/ioc2rpz"
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]: ioc2rpz version: "1.1.2.3-2020123101", IP:  , PID: <0.531.0>, Config: "./cfg/ioc2rpz.conf"
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]: Get AXFR zone "eu-ordered-bl.ioc2rpz" serial 0 status notready cache "true"
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]: Get IXFR zone "eu-ordered-bl.ioc2rpz" serial 0 status notready
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]: Get AXFR zone "court-ordered-bl.ioc2rpz" serial 0 status notready cache "true"
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]: Get IXFR zone "court-ordered-bl.ioc2rpz" serial 0 status notready
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]: Get AXFR zone "miners-bl.ioc2rpz" serial 0 status notready cache "true"
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]: Get IXFR zone "miners-bl.ioc2rpz" serial 0 status notready
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]: Get AXFR zone "adware-bl.ioc2rpz" serial 0 status notready cache "true"
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]: Get IXFR zone "adware-bl.ioc2rpz" serial 0 status notready
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]: Get AXFR zone "gambling-bl.ioc2rpz" serial 0 status notready cache "true"
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]: Get IXFR zone "gambling-bl.ioc2rpz" serial 0 status notready
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]: Get AXFR zone "malware-bl.ioc2rpz" serial 0 status notready cache "true"
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]: Get IXFR zone "malware-bl.ioc2rpz" serial 0 status notready
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]: RPZ "malware-bl.ioc2rpz" was not loaded. No sources. Sources false Whitelists true.
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]: RPZ "gambling-bl.ioc2rpz" was not loaded. No sources. Sources false Whitelists true.
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]: =CRASH REPORT==== 13-Nov-2023::15:51:54.055791 ===                                                                                                       Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]:   crasher:                                                                                                                                               Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]:     initial call: application_master:init/4                                                                                                              Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]:     pid: <0.529.0>
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]:     registered_name: []                                                                                                                                  Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]:     exception exit: {{{badrecord,rpz},
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]:                       [{ioc2rpz_sup,'-read_config3/8-lc$^20/1-19-',1,
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]:                                     [{file,"/opt/ioc2rpz/src/ioc2rpz_sup.erl"},
Nov 13 16:51:54 rpz.domain.com c7735b7e2425[2981461]:                                      {line,268}]},
```

**Comment by dmgeurts** [comment]
My experience with Docker is limited.

I'm currently exploring why ioc2rpz starts when I disable two of my RPZs. And if I then enable one of these two, ioc2rpz doesn't crash, but if I restart ioc2rpz it does crash.

This log entry makes no sense to me: `RPZ "gambling-bl.ioc2rpz" was not loaded. No sources. Sources false Whitelists true.`

If I run `grep -E <regex>` against the file then I get all the lines with the domains in question. This file does use tab to delimit domains, could that be an issue?

**Comment by dmgeurts** [comment]
Hmmm, I seem to have a few issues...

1. https://github.com/Homas/ioc2rpz.gui/issues/14
2. I have two source lists which cause ioc2rpz to crash
3. RPZ not found error as ioc2rpz config isn't updated by ioc2rpz.gui with the new source nor the new RPZ

As this issue is about #3, I'll try to restrict logs to that.

I've just manually created the source and RPZ entry in the config and then the RPZ zone works fine and ioc2rpz is happy to serve content.

**Comment by dmgeurts** [comment]
For the time being I'm editing the ioc2rpz.conf file manually as ioc2rpz.gui makes a complete hash of it at the moment. I see no errors from ioc2rpz.gui in the systemd journal. Is there any way I can best troubleshoot this?

Also, I'm not that partial to docker, I run ioc2rpz and ioc2rpz.gui on a dedicated VM. So I'm curious if it wouldn't be easier for me to run ioc2rpz natively. Are there instructions on how to do so?

**Comment by Homas** [comment]
It did crash due to a bad config. Please upgrade to the newest versions. Containers on the dockerhub are deprecated. 
> if it wouldn't be easier for me to run ioc2rpz natively

It will not be easier. Please use a docker compose file from [ioc2rpz.dc](https://github.com/Homas/ioc2rpz.dc) repository (most easiest way).

**Comment by dmgeurts** [comment]
Problem solved after upgrading
