### ISSUE TITLE
Example of RPZ: Local Records Option

### ISSUE THREAD

**Issue by Yvtq8K3n** [Homas/ioc2rpz.gui#6]
Could you provide an example of how to use it? I tried a few things but didn't get much success.

**Comment by Homas** [comment]
Just rechecked the code. Multiple records are supported. You need to create a single record per line.
I'm going to document that and add rules validation.

**Comment by Homas** [comment]
Fixed in the dev branch. I'll merge it to the main branch when finish all planned updates including integration with RpiDNS. ETA - early July.
