### ISSUE TITLE
UX/UI for hot cache time per source and RPZ

### ISSUE THREAD

**Issue by Homas** [Homas/ioc2rpz.gui#9]
UX/UI for hot cache time per source, continue https://github.com/Homas/ioc2rpz/issues/32

**Comment by Homas** [comment]
@mk-git I've pushed UX/UI update into the dev branch. The update looks a bit ugly but functional. 
Please take a look.

**Comment by mk-git** [comment]
With me it works so far. I'll have to look through the logfile again later, but at least yesterday it already worked wonderfully. Today with the GUI it will be even easier.

A very small improvement idea for the GUI: It may not be clear to everyone that the value is then in seconds (so it has a description for WHAT the value is, but not in what unit (minutes, seconds?)

**Comment by Homas** [comment]
Good point. Fixed.
